import { defineConfig } from 'vitest/config'
import { fileURLToPath } from 'node:url'

// Standalone rather than a `test` block inside vite.config.ts: that file is
// generated by Figma Make and gets overwritten, and its plugins are for serving
// the app, not for running tests.
export default defineConfig({
  resolve: {
    alias: { '@': fileURLToPath(new URL('./src', import.meta.url)) },
  },
  test: {
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    include: ['src/**/*.test.{ts,tsx}'],
    restoreMocks: true,
    // Vite loads .env.local during tests too, so without this the suite would
    // depend on whether the developer happens to have configured OAuth — green
    // on CI, red on their machine. Tests that care stub these themselves.
    env: {
      VITE_GOOGLE_CLIENT_ID: '',
      VITE_APPLE_CLIENT_ID: '',
      VITE_FACEBOOK_APP_ID: '',
    },
  },
})
